### ISSUE TITLE
Not working in Heroku

### ISSUE THREAD

**Issue by hideokamoto** [Shopify/shopify-app-node#529] opened 2021-02-07 15:04 UTC
# Issue summary

I've created a new project by the CLI and deploy it to heroku.
But the application does not work in Heroku.
I got the `Internal Server Error` in the Shopify application.

## Expected behavior

When accessing the application in the Shopify store admin,
we can see the default content.

## Actual behavior

I got `Internal Server Error`.
![スクリーンショット 2021-02-08 0 00 35](https://user-images.githubusercontent.com/6883571/107150374-d9852e80-69a0-11eb-8c98-924eee1a43f3.png)

## Steps to reproduce the problem

```bash
$ shopify create node
$ shopify deploy heroku
```

And put the Heroku's application domain to the application detail page.
![スクリーンショット 2021-02-08 0 02 54](https://user-images.githubusercontent.com/6883571/107150414-05081900-69a1-11eb-8aa3-f1217dd09143.png)

And I got these error to run `heroku logs`.

````
2021-02-07T15:00:29.233915+00:00 app[web.1]: 
2021-02-07T15:00:29.233957+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
2021-02-07T15:00:29.233959+00:00 app[web.1]: at prepareSecretKey (internal/crypto/keys.js:322:11)
2021-02-07T15:00:29.233959+00:00 app[web.1]: at new Hmac (internal/crypto/hash.js:111:9)
2021-02-07T15:00:29.233960+00:00 app[web.1]: at Object.createHmac (crypto.js:147:10)
2021-02-07T15:00:29.233960+00:00 app[web.1]: at sign (/app/node_modules/keygrip/index.js:23:8)
2021-02-07T15:00:29.233961+00:00 app[web.1]: at Keygrip.sign (/app/node_modules/keygrip/index.js:30:38)
2021-02-07T15:00:29.233961+00:00 app[web.1]: at Cookies.set (/app/node_modules/cookies/index.js:110:30)
2021-02-07T15:00:29.233962+00:00 app[web.1]: at topLevelOAuthRedirect (/app/node_modules/@shopify/koa-shopify-auth/dist/src/auth/create-top-level-oauth-redirect.js:10:21)
2021-02-07T15:00:29.233963+00:00 app[web.1]: at /app/node_modules/@shopify/koa-shopify-auth/dist/src/auth/index.js:61:46
2021-02-07T15:00:29.233963+00:00 app[web.1]: at step (/app/node_modules/tslib/tslib.js:133:27)
2021-02-07T15:00:29.233963+00:00 app[web.1]: at Object.next (/app/node_modules/tslib/tslib.js:114:57)
2021-02-07T15:00:29.233964+00:00 app[web.1]: 

````

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Firefox
- Device: macOS
- Operating System:

**Comment by paulomarg** [comment] 2021-02-08 14:48
Hey @hideokamoto, I believe this could be happening because you haven't set up your environment variables on your Heroku app.

You can go to your Heroku app's dashboard and set up the values in your `.env` file as variables, which should solve that issue.

**Comment by hideokamoto** [comment] 2021-02-15 09:42
Works well!!
Thanks a lot :)

![スクリーンショット 2021-02-15 18 40 12](https://user-images.githubusercontent.com/6883571/107929824-8bce7e80-6fbd-11eb-8d61-b56aef7c90f1.png)

![スクリーンショット 2021-02-15 18 40 00](https://user-images.githubusercontent.com/6883571/107929822-8a04bb00-6fbd-11eb-91a2-5ce596a3b7a1.png)

**Comment by paulomarg** [comment] 2021-02-17 13:41
Great to hear, happy coding! Closing this issue since the problem is solved.

**Closed by paulomarg** 2021-02-17 13:41 UTC
